---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-configmap
  namespace: immich
data:
  DB_DATABASE_NAME: immich
  DB_HOSTNAME: immich-postgres-postgresql.immich.svc.cluster.local
  DB_PORT: "5432"
  DISABLE_REVERSE_GEOCODING: "true"
  ENABLE_MAPBOX: "false"
  LOG_LEVEL: verbose
  NODE_ENV: "production"
  REDIS_HOSTNAME: immich-redis-master.immich.svc.cluster.local
  REDIS_PORT: "6379"
  REDIS_DBINDEX: "0"
  IMMICH_WEB_URL: http://immich-web.immich.svc.cluster.local:3000
  IMMICH_SERVER_URL: http://immich-server.immich.svc.cluster.local:3001
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.immich.svc.cluster.local:3003
