---
# yaml-language-server: $schema=https://crd.movishell.pl/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app renovate-operator
  namespace: &namespace github
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  path: ./kubernetes/apps/github/renovate/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-ops
    namespace: flux-system
  targetNamespace: *namespace
---
# yaml-language-server: $schema=https://crd.movishell.pl/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app renovate-jobs
  namespace: &namespace github
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: renovate-operator
      namespace: *namespace
    - name: external-secrets
      namespace: security
  interval: 30m
  path: ./kubernetes/apps/github/renovate/jobs
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-ops
    namespace: flux-system
  targetNamespace: *namespace
  wait: false
