---
collections:
  - name: community.general
    version: 5.2.0
  - name: community.sops
    version: 1.2.2
  - name: ansible.posix
    version: 1.4.0
roles:
  - src: xanmanning.k3s
    version: v3.2.0
