---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cluster.yaml
  - ./cluster-17.yaml
  - ./externalsecret.yaml
  - ./immich.yaml
  - ./immich-pg17.yaml
  - ./objectstore.yaml
  - ./podmonitor.yaml
  - ./prometheusrule.yaml
  - ./scheduledbackup.yaml
  - ./service.yaml
