---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./bgpadvertisement.yaml
  # - ./bgppeer.yaml
  - ./ipaddresspool.yaml
  - ./l2advertisement.yaml
