---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik-charts.yaml
  - backube-charts.yaml
  - bitnami-charts.yaml
  - bjw-s-charts.yaml
  - cloudnative-pg-charts.yaml
  - democratic-csi-charts.yaml
  - ext-postgres-operator-charts.yaml
  - external-dns-charts.yaml
  - external-secrets-charts.yaml
  - fairwinds-charts.yaml
  - grafana-charts.yaml
  - hajimari-charts.yaml
  - ingress-nginx-charts.yaml
  - jetstack-charts.yaml
  - k8s-at-home-charts.yaml
  - k8s-gateway-charts.yaml
  - kubereboot-charts.yaml
  - metallb-charts.yaml
  - metrics-server-charts.yaml
  - minecraft-server-charts.yaml
  - nextcloud-charts.yaml
  - piraeus-charts.yaml
  - prometheus-community.yaml
  - stakater-charts.yaml
  - truenas-csp.yaml
  - weave-gitops-charts.yaml
  - vector-charts.yaml
