apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - democratic-csi.yaml
  - hajimari-charts.yaml
  - ingress-nginx-charts.yaml
  - jetstack-charts.yaml
  - k8s-at-home-charts.yaml
  - metallb-charts.yaml
  - metrics-server-charts.yaml
  - minecraft-server-charts.yaml
  - nextcloud-charts.yaml
  - stakater-charts.yaml
  - truenas-csp.yaml
