---
# yaml-language-server: $schema=https://crd.movishell.pl/traefik.io/middleware_v1alpha1.json
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: errorpages
spec:
  errors:
    status:
      - "500"
      - "501"
      - "503"
      - "505-599"
    query: /{status}.html
    service:
      name: error-pages
      namespace: network
      port: 8080
