---
# yaml-language-server: $schema=https://crd.movishell.pl/traefik.io/middleware_v1alpha1.json
apiVersion: traefik.io/v1_alpha1
kind: Middleware
metadata:
  name: error-pages
spec:
  errors:
    status: ["401", "403", "404", "500-599"]
    service:
      name: error-pages
      port: 8080 # : "{{ .appName }}-service", port: 8080}
    query: "/{status}.html"
