---
# yaml-language-server: $schema=https://crd.movishell.pl/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate-operator
spec:
  chartRef:
    kind: OCIRepository
    name: renovate-operator
  interval: 30m
  values:
    fullnameOverride: renovate-operator
    route:
      annotations:
        gatus.home-operations.com/endpoint: "name: renovate-operator"
      enabled: true
      hostnames: ["renovate.${PRIVATE_DOMAIN}"]
      parentRefs:
        - name: envoy-internal
          namespace: network
          sectionName: https
    webhook:
      enabled: true
