---
# yaml-language-server: $schema=https://crd.movishell.pl/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: renovate-operator
  annotations:
    gatus.home-operations.com/endpoint: |-
      name: renovate-oeprator
spec:
  hostnames: ["renovate.${PRIVATE_DOMAIN}"]
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - group: gateway.envoyproxy.io
          kind: Service
          name: renovate-operator
          port: 8081
      matches:
        - path:
            type: PathPrefix
            value: /
