---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name onepassword-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        1password-credentials.json: "{{ .OP_CREDENTIALS_JSON }}"
        token: "{{ .OP_CONNECT_TOKEN }}"
        ESO_TOKEN: "{{ .ESO_TOKEN }}"
  dataFrom:
    - extract:
        key: op-connect
---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name onepassword-secret-test
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-sdk
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        1password-credentials.json: "{{ .OP_CREDENTIALS_JSON }}"
        tokenfoo: "{{ .OP_CONNECT_TOKEN }}"
        ESO_TOKEN: "{{ .ESO_TOKEN }}"
  dataFrom:
    - extract:
        key: op-connect
