---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./certificate.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: mediamtx-configmap
    namespace: media
    files:
      - mediamtx.yml=./config/config.yaml
generatorOptions:
  disableNameSuffixHash: true
