---
# yaml-language-server: $schema=https://crd.movishell.pl/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: minecraft-map-test
  annotations:
    gatus.home-operations.com/endpoint: |-
      name: minecraft
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Games
    gethomepage.dev/name: Minecraft
    gethomepage.dev/icon: minecraft.svg
    gethomepage.dev/pod-selector: app.kubernetes.io/name=minecraft
    gethomepage.dev/widget.type: minecraft
    gethomepage.dev/widget.url: udp://minecraft.games:25565
spec:
  hostnames: ["${MAP_HOSTNAME}"]
  parentRefs:
    - name: envoy-external
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: minecraft-map
          port: 8100
      matches:
        - path:
            type: PathPrefix
            value: /
