---
# yaml-language-server: $schema=https://crd.movishell.pl/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name garage
spec:
  staticConfigs: [targets: ["garage-api.${PRIVATE_DOMAIN}"]]
  metricsPath: /metrics
  scheme: HTTPS
  authorization:
    type: Bearer
    credentials:
      key: GARAGE_METRICS_TOKEN
      name: garage-scraper-secret
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
