---
# yaml-language-server: $schema=https://crd.movishell.pl/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name speedtest-exporter
spec:
  staticConfigs: [targets: ["leo.${PRIVATE_DOMAIN}:9798"]]
  metricsPath: /metrics
  scrapeInterval: 60m
  scrapeTimeout: 60s
  honorTimestamps: true
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
    - sourceLabels: [__address__]
      regex: '([^:]+):\d+'
      replacement: "$1"
      targetLabel: instance
---
# yaml-language-server: $schema=https://crd.movishell.pl/grafana.integreatly.org/grafanadashboard_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: speedtest-exporter
spec:
  allowCrossNamespaceImport: true
  datasources:
    - datasourceName: prometheus
      inputName: DS_PROMETHEUS
  folder: Networking
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
  url: https://grafana.com/api/dashboards/13665/revisions/4/download
