---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name openwebui-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        WEBUI_SECRET_KEY: "{{ .SECRET_KEY }}"
        # OIDC
        OAUTH_CLIENT_ID: "{{ .OIDC_CLIENT_ID }}"
        OAUTH_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
        OPENID_PROVIDER_URL: https://auth.${PUBLIC_DOMAIN}/.well-known/openid-configuration
        OPENID_REDIRECT_URI: https://ai.${PRIVATE_DOMAIN}/oauth/oidc/callback
        # Postgres
        INIT_POSTGRES_DBNAME: openwebui
        INIT_POSTGRES_HOST: postgres-17-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        DATABASE_URL: postgres://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASS }}@postgres-17-rw.database.svc.cluster.local:5432/openwebui
        # Redis
        ENABLE_WEBSOCKET_SUPPORT: "true"
        WEBSOCKET_MANAGER: "redis"
        REDIS_URL: "redis://dragonfly.database.svc.cluster.local:6379/7"
        WEBSOCKET_REDIS_URL: "redis://dragonfly.database.svc.cluster.local:6379/7"
  dataFrom:
    - extract:
        key: openwebui
    - extract:
        key: cloudnative-pg
