---
# yaml-language-server: $schema=https://crd.movishell.pl/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minecraft-test
  namespace: &namespace games
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: &appname minecraft-test
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: external-secrets
      namespace: security
    - name: volsync
      namespace: storage
  interval: 30m
  path: ./kubernetes/apps/games/minecraft-test/app
  postBuild:
    substitute:
      APP: *appname
      HOSTNAME: minecraft-test.${PRIVATE_DOMAIN}
      MAP_HOSTNAME: dynmap-test.${PRIVATE_DOMAIN}
      APP_UID: "568"
      APP_GID: "568"
      PVC_CLAIM: minecraft-data-test
      PVC_CAPACITY: 15Gi
      VOLSYNC_CACHE_CAPACITY: 15Gi
      PVC_STORAGECLASS: &nvme dcsi-nvmeof
      VOLSYNC_SNAPSHOTCLASS: *nvme
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-ops
    namespace: flux-system
  targetNamespace: *namespace
  wait: false
