---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: minecraft-server
  namespace: flux-system
spec:
  interval: 1h
  url: https://itzg.github.io/minecraft-server-charts/
  timeout: 3m
