---
# yaml-language-server: $schema=https://crd.movishell.pl/gateway.networking.k8s.io/gateway_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-internal
  annotations:
    gatus.home-operations.com/endpoint: |-
      group: internal
      ui:
        hide-hostname: true
        hide-url: true
      alerts:
        - type: pushover
          send-on-resolved: true
  labels:
    type: internal
    role: production
spec:
  gatewayClassName: envoy
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: default-private-certificate
---
# yaml-language-server: $schema=https://crd.movishell.pl/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: envoy-internal
spec:
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: http
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
---
# yaml-language-server: $schema=https://crd.movishell.pl/gateway.envoyproxy.io/envoyextensionpolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyExtensionPolicy
metadata:
  name: lua-test-internal
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: external
  lua:
    - type: Inline
      inline: |
        local host_country_map = {
            ["movishell.pl"] = "pl",
            ["ishioni.casa"] = "casa",
        }
        -- Function called on each HTTP request
        function envoy_on_request(request_handle)
            -- Get the host header from the incoming request
            local host = request_handle:headers():get("host")

            if host then
                -- Look up the country code for this host
                local country = host_country_map[host]

                if country then
                    -- Add X-App-Id header with the country code
                    request_handle:headers():add("X-App-Id", country)
                end
            else
                -- Optional: handle requests with no host header
                request_handle:headers():add("X-App-Id", "unknown")
            end
        end
