---
# yaml-language-server: $schema=https://crd.movishell.pl/gateway.networking.k8s.io/referencegrant_v1beta1.json
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: listener-debug-public
spec:
  from:
    - group: gateway.networking.x-k8s.io
      kind: XListenerSet
      namespace: default
  to:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: envoy-external
---
# yaml-language-server: $schema=https://crd.movishell.pl/gateway.networking.k8s.io/referencegrant_v1beta1.json
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: listener-debug-private
spec:
  from:
    - group: gateway.networking.x-k8s.io
      kind: XListenerSet
      namespace: default
  to:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: envoy-internal
