---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana
  - nut-exporter
  - pve-exporter
  - kube-prometheus-stack
  - speedtest-exporter
  - thanos
  - uptime-kuma
  - weave-gitops
  - unpoller
