---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tandoor-configmap
  namespace: fileserver
data:
  DEBUG: "0"
  ALLOWED_HOSTS: "*"
  DB_ENGINE: django.db.backends.postgresql
  GUNICORN_MEDIA: "0"
  TIMEZONE: Europe/Warsaw
  TANDOOR_PORT: "8080"
  FRACTION_PREF_DEFAULT: "0"
  COMMENT_PREF_DEFAULT: "1"
  SHOPPING_MIN_AUTOSYNC_INTERVAL: "5"
  SOCIAL_PROVIDERS: allauth.socialaccount.providers.openid_connect
  ENABLE_SIGNUP: "1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tandoor-nginx
  namespace: fileserver
data:
  nginx-config: |
    events {
      worker_connections 1024;
    }
    http {
      include mime.types;
      server {
        listen 80;
        server_name _;
        client_max_body_size 128M;
        # serve static files
        location /static/ {
          alias /static/;
        }
        # serve media files
        location /media/ {
          alias /media//;
        }
        # pass requests for dynamic content to gunicorn
        location / {
        proxy_set_header Host $host;
        proxy_pass http://localhost:8080;
        }
      }
    }
