---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  PUBLIC_DOMAIN: movishell.pl
  PRIVATE_DOMAIN: ishioni.casa
  NAS_DOMAIN: nas.ishioni.casa
  CONFIG_BGP_POOL_CIDR: 10.84.2.0/24
  CONFIG_INGRESS_PUBLIC_IP: 10.84.2.2
  CONFIG_INGRESS_PRIVATE_IP: 10.84.2.3
  CONFIG_TRANSMISSION_IP: 10.84.2.4
  CONFIG_MINECRAFT_IP: 10.84.2.5
  CONFIG_QBITTORRENT_IP: 10.84.2.6
  CONFIG_TRUENAS_IP: 10.1.2.2
  CONFIG_TIMEZONE: Europe/Warsaw
  CONFIG_MEDIA_UID: "2000"
  CONFIG_APP_UID: "568"
  CONFIG_APP_GID: "568"
