---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  HOME_DOMAIN: ishioni.casa
  CONFIG_BGP_POOL_CIDR: 192.168.3.0/24
  CONFIG_GATEWAY_DNS_IP: 192.168.3.1
  CONFIG_INGRESS_PUBLIC_IP: 192.168.3.2
  CONFIG_INGRESS_PRIVATE_IP: 192.168.3.3
  CONFIG_TRANSMISSION_IP: 192.168.3.4
  CONFIG_MINECRAFT_IP: 192.168.3.5
  CONFIG_POSTGRES_IP: 192.168.3.6
  CONFIG_UT99_IP: 192.168.3.7
  CONFIG_MEDIAMTX_IP: 192.168.3.8
  CONFIG_LOKI_IP: 192.168.3.9
  CONFIG_VECTOR_IP: 192.168.3.10
  CONFIG_TRUENAS_IP: 10.1.4.2
  CONFIG_TIMEZONE: Europe/Warsaw
  CONFIG_MEDIA_UID: "2000"
  CONFIG_APP_UID: "568"
  CONFIG_APP_GID: "568"
