---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name ishioni-bot-pem
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        PRIVATE_KEY: "{{ .PRIVATE_KEY }}"
  dataFrom:
    - extract:
        key: actions-runner-controller
---
# yaml-language-server: $schema=https://crd.movishell.pl/generators.external-secrets.io/githubaccesstoken_v1alpha1.json
apiVersion: generators.external-secrets.io/v1alpha1
kind: GithubAccessToken
metadata:
  name: ishioni-bot-auth-token
spec:
  appID: "250916"
  installID: "30398545"
  auth:
    privateKey:
      secretRef:
        name: ishioni-bot-pem # reference secret from step 1.
        key: PRIVATE_KEY
---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ishioni-bot-token
spec:
  refreshInterval: "30m0s"
  target:
    name: ishioni-bot-token
    template:
      type: Opaque
      engineVersion: v2
      data:
        GITHUB_COM_TOKEN: "{{ .token }}"
        GITHUB_COM_USER: aXNoaW9uaQ==
        RENOVATE_TOKEN: "{{ .token }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: GithubAccessToken
          name: ishioni-bot-auth-token
