---
# yaml-language-server: $schema=https://crd.movishell.pl/renovate-operator.mogenius.com/renovatejob_v1alpha1.json
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: ishioni
spec:
  discoverTopics: renovate
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_ALLOWED_COMMANDS
      value: '["pnpm run bundle"]'
    - name: RENOVATE_ENDPOINT
      value: https://api.github.com/
    - name: RENOVATE_PLATFORM
      value: github
    - name: RENOVATE_PLATFORM_COMMIT
      value: "true"
  image: ghcr.io/renovatebot/renovate:43.3.6
  parallelism: 5
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: 0 * * * *
  secretRef: ishioni-bot-token
  webhook:
    enabled: true
