---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name grafana-instance-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        # App
        # GF_SECURITY_ADMIN_USER: "{{ .ADMIN_USER }}"
        GF_SECURITY_ADMIN_PASSWORD: "{{ .ADMIN_PASSWORD }}"
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{ .OIDC_CLIENT_ID }}"
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
        # GF_DATABASE_NAME: &dbname grafana-instance
        # GF_DATABASE_HOST: &dbhost postgres-rw.database.svc.cluster.local
        # GF_DATABASE_USER: &dbuser "{{ .POSTGRES_USER }}"
        # GF_DATABASE_PASSWORD: &dbpass "{{ .POSTGRES_PASS }}"
        # Postgres init
        # INIT_POSTGRES_DBNAME: *dbname
        # INIT_POSTGRES_HOST: *dbhost
        # INIT_POSTGRES_USER: *dbuser
        # INIT_POSTGRES_PASS: *dbpass
        # INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: grafana
    - extract:
        key: cloudnative-pg
