---
# yaml-language-server: $schema=https://crd.movishell.pl/grafana.integreatly.org/grafanafolder_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: kubernetes
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana-instance
  title: Kubernetes
---
# yaml-language-server: $schema=https://crd.movishell.pl/grafana.integreatly.org/grafanafolder_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: networking
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana-instance
  title: Networking
---
# yaml-language-server: $schema=https://crd.movishell.pl/grafana.integreatly.org/grafanafolder_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: operators
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana-instance
  title: Operators
---
# yaml-language-server: $schema=https://crd.movishell.pl/grafana.integreatly.org/grafanafolder_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: storage
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana-instance
  title: Storage
---
# yaml-language-server: $schema=https://crd.movishell.pl/grafana.integreatly.org/grafanafolder_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: system
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana-instance
  title: System
