---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name qui-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        # App
        QUI__SESSION_SECRET: "{{ .SESSION_SECRET }}"
        # OIDC
        QUI__OIDC_ENABLED: "true"
        QUI__OIDC_ISSUER: "https://auth.movishell.pl/application/o/qui/"
        QUI__OIDC_CLIENT_ID: "{{ .OIDC_CLIENT_ID }}"
        QUI__OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
        QUI__OIDC_REDIRECT_URL: "https://${HOSTNAME}/api/auth/oidc/callback"
        QUI__OIDC_DISABLE_BUILT_IN_LOGIN: "true"
  dataFrom:
    - extract:
        key: qui
