---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.5.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app http-debug
spec:
  chartRef:
    kind: OCIRepository
    name: http-debug
  interval: 30m
  values:
    controllers:
      http-debug:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/ishioni/http-debug
              tag: 0.0.3
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    port: &port 8080
              readiness: *probes
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    route:
      app:
        annotations:
          gatus.home-operations.com/enabled: "false"
        hostnames: ["http-debug.${PUBLIC_DOMAIN}"]
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - kind: Service
                name: *app
                port: *port
      pl:
        annotations:
          gatus.home-operations.com/enabled: "false"
        hostnames: ["pl.http-debug.${PUBLIC_DOMAIN}"]
        parentRefs:
          - group: gateway.networking.x-k8s.io
            kind: XListenerSet
            name: http-debug-listener-public
            namespace: default
            sectionName: https
        rules:
          - backendRefs:
              - kind: Service
                name: *app
                port: *port
      es:
        annotations:
          gatus.home-operations.com/enabled: "false"
        hostnames: ["es.http-debug.${PUBLIC_DOMAIN}"]
        parentRefs:
          - group: gateway.networking.x-k8s.io
            kind: XListenerSet
            name: http-debug-listener-public
            namespace: default
            sectionName: https
        rules:
          - backendRefs:
              - kind: Service
                name: *app
                port: *port
      tr:
        annotations:
          gatus.home-operations.com/enabled: "false"
        hostnames: ["tr.http-debug.${PUBLIC_DOMAIN}"]
        parentRefs:
          - group: gateway.networking.x-k8s.io
            kind: XListenerSet
            name: http-debug-listener-public
            namespace: default
            sectionName: https
        rules:
          - backendRefs:
              - kind: Service
                name: *app
                port: *port
    ingress:
      app:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.middlewares: error-pages@kubernetescrd
        className: traefik
        hosts:
          - host: &host http-debug.traefik.ishioni.casa
            paths:
              - path: /
                service:
                  name: *app
                  port: *port
        tls:
          - hosts:
              - *host
            secretName: *host
