---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # renovate: datasource=github-releases depName=cloudnative-pg/plugin-barman-cloud
  - https://raw.githubusercontent.com/cloudnative-pg/plugin-barman-cloud/refs/tags/${SIDECAR_IMAGE_VERSION}/config/crd/bases/barmancloud.cnpg.io_objectstores.yaml
  - ./certificate.yaml
  - ./helmrelease.yaml
  - ./rbac.yaml
