---
# yaml-language-server: $schema=https://crd.movishell.pl/gateway.envoyproxy.io/backendtrafficpolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: envoy-test-redirects
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: whoami-test
  responseOverride:
    - match:
        statusCodes:
          - type: Range
            range:
              end: 410
              start: 400
      redirect:
        path:
          type: ReplaceFullPath
          replaceFullPath: /error
        statusCode: 302
