---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
data:
  PUBLIC_DOMAIN: movishell.pl
  PRIVATE_DOMAIN: ishioni.casa
  CONFIG_BGP_PUBLIC_POOL_CIDR: 10.84.2.0/27
  CONFIG_BGP_PRIVATE_POOL_CIDR: 10.84.2.32/27
  CONFIG_L2_POOL_PUBLIC_CIDR: 10.1.2.96/27
  CONFIG_L2_POOL_PRIVATE_CIDR: 10.1.2.128/27
  # CONFIG_INGRESS_PUBLIC_IP: 10.1.2.96
  # CONFIG_QBITTORRENT_IP: 10.1.2.97
  # CONFIG_MINECRAFT_IP: 10.1.2.98
  CONFIG_INGRESS_PUBLIC_IP: 10.84.2.1
  CONFIG_QBITTORRENT_IP: 10.84.2.2
  CONFIG_MINECRAFT_IP: 10.84.2.3
  CONFIG_GO2RTC_IP: 10.84.2.4
  CONFIG_TRUENAS_IP: 10.1.2.2
  CONFIG_TIMEZONE: Europe/Warsaw
  CONFIG_MEDIA_UID: "5000"
  CONFIG_APP_UID: "568"
  CONFIG_APP_GID: "568"
