---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name readur-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        # Database
        DATABASE_HOST: &dbhost postgres-rw.database.svc.cluster.local
        POSTGRES_DB: &dbname readur
        POSTGRES_USER: &dbuser "{{ .POSTGRES_USER }}"
        POSTGRES_PASSWORD: &dbpass "{{ .POSTGRES_PASS }}"
        # App
        JWT_SECRET: "{{ .JWT_SECRET }}"
        # OIDC
        OIDC_CLIENT_ID: "{{ .OIDC_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
        OIDC_REDIRECT_URI: "https://${HOSTNAME}/api/auth/oidc/callback"
        OIDC_ISSUER_URL: https://auth.${PUBLIC_DOMAIN}/application/o/readur/
        OIDC_AUTO_REGISTER: "true"
        ALLOW_LOCAL_AUTH: "false"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: readur
    - extract:
        key: cloudnative-pg
