---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitor
resources:
  - ./alertmanager.yaml
  - ./externalsecret.yaml
  - ./grafanadashboard.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./scrapeconfigs
configMapGenerator:
  - name: kube-state-metrics-config
    files:
      - kube-state-metrics.yaml=./config/kube-state-metrics.yaml
generatorOptions:
  disableNameSuffixHash: true
