---
# yaml-language-server: $schema=https://crd.movishell.pl/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
spec:
  chartRef:
    kind: OCIRepository
    name: traefik
  interval: 30m
  values:
    deployment:
      replicas: 1
    ingressClass:
      name: traefik
    gateway:
      enabled: false
    gatewayClass:
      enabled: false
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
      kubernetesIngress:
        allowExternalNameServices: true
      file:
        enabled: false
        content: |
          http:
            middlewares:
              global-errors:
                errors:
                  status: ["401", "403", "404", "500-599"]
                  service: global-error-pages
                  query: "/{status}.html"

            services:
              global-error-pages:
                loadBalancer:
                  servers:
                    - url: http://error-pages.network.svc.cluster.local:8080
    ports:
      web:
        http:
          middlewares:
            - error-pages

    logs:
      access:
        enabled: true
