---
# yaml-language-server: $schema=https://crd.movishell.pl/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: backube
  namespace: flux-system
spec:
  url: https://backube.github.io/helm-charts/
  interval: 1h
  timeout: 3m
