---
api:
  dashboard: true
accesslog: {}
  # format: json
  # fields:
  #   defaultMode: keep
  #   headers:
  #     defaultMode: keep
log:
  level: INFO #DEBUG
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
    http3:
providers:
  docker:
    network: apps
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /dynamic
certificatesResolvers:
  letsencrypt:
    acme:
      email: homelab@movishell.pl
      storage: /certs/acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 2s #Optional to wait x second before checking with the DNS Server
        resolvers:
          - 1.1.1.1:53
tls:
  stores:
    default:
      defaultGeneratedCert:
        resolver: letsencrypt
        domain:
          main: ishioni.casa
          sans:
            - "*.ishioni.casa"
metrics:
  prometheus:
    entryPoint: metrics
    manualRouting: true
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
