---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./gatus.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
configMapGenerator:
  - name: opencloud
    files:
      - csp.yaml=./config/csp.yaml
      - proxy.yaml=./config/proxy.yaml
configurations:
  - ./config/kustomizeconfig.yaml
