---
# yaml-language-server: $schema=https://crd.movishell.pl/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: flux-status
  annotations:
    gatus.home-operations.com/endpoint: |-
      name: flux-operator
spec:
  hostnames: [flux-operator.ishioni.casa]
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - group: gateway.envoyproxy.io
          kind: Service
          name: flux-operator
          port: 9080
      matches:
        - path:
            type: PathPrefix
            value: /
