---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name dcsi-nvmeof-test-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        driver-config-file.yaml: |
          driver: freenas-api-nvmeof
          httpConnection:
            protocol: http
            host: "truenas.ishioni.casa"
            port: "80"
            apiKey: {{ .TEST_API_TOKEN }}
            allowInsecure: true
          zfs:
            datasetProperties:
              "org.freenas:description": "{{`{{ parameters.[csi.storage.k8s.io/pvc/name] }}`}}"
            datasetParentName: TEST/talos/applications
            detachedSnapshotsDatasetParentName: TEST/talos/snapshots
            zvolCompression: gzip
            zvolDedup: false
            zvolEnableReservation: false
            zvolBlocksize: 16K
          nvmeof:
            transports: tcp://truenas.ishioni.casa:4420
            namePrefix: csi-
            nameSuffix: "-nvmeof"
            ports:
              - 1
            subsystemTemplate:
              pi_enable: true
              qid_max:
              ieee_oui:
              ana:
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: democratic-csi
