---
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
sonarr:
  main:
    base_url: http://sonarr.downloads.svc.cluster.local
    api_key: !env_var SONARR_API_KEY

    # Custom Format Configuration
    delete_old_custom_formats: true
    media_management:
      propers_and_repacks: do_not_prefer

    quality_profiles:
      - name: WEB-1080p
        trash_id: 72dae194fc92bf828f32cde7744e51a1
        reset_unmatched_scores:
          enabled: true
      - name: WEB-2160p
        trash_id: c4cadd6b35b95f62c3d47a408ea53e2f7
        reset_unmatched_scores:
          enabled: true

    custom_formats:
      - trash_ids:
          - 9b27ab6498ec0f31a3353992e19434ca # DV (WEBDL)
        assign_scores_to:
          - name: WEB-2160p
      - # Unwanted
        trash_ids:
          - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          - 06d66ab109d4d2eddb2794d21526d140 # Retags
          - 1b3994c551cbb92a2c781af061f4ab44 # Scene
        assign_scores_to:
          - name: WEB-1080p
          - name: WEB-2160p

radarr:
  standard:
    base_url: http://radarr.downloads.svc.cluster.local
    api_key: !env_var RADARR_API_KEY

    # Custom Format Configuration
    delete_old_custom_formats: true
    media_management:
      propers_and_repacks: do_not_prefer

    quality_definition:
      type: movie

    quality_profiles:
      - name: UHD
        reset_unmatched_scores:
          enabled: true
        upgrade:
          allowed: false
          until_quality: Remux-2160p
          until_score: 10000
        min_format_score: 0
        quality_sort: top
        qualities:
          - name: Remux-2160p
          - name: WEB 2160p
            qualities:
              - WEBDL-2160p
              - WEBRip-2160p
      - name: HD
        reset_unmatched_scores:
          enabled: true
        upgrade:
          allowed: false
          until_quality: Remux-1080p
          until_score: 10000
        min_format_score: 0
        quality_sort: top
        qualities:
          - name: Remux-1080p
          - name: WEB 1080p
            qualities:
              - WEBDL-1080p
              - WEBRip-1080p
      - name: SD
        reset_unmatched_scores:
          enabled: true
        upgrade:
          allowed: true
          until_quality: WEB 720p
          until_score: 10000
        min_format_score: 0
        quality_sort: top
        qualities:
          - name: Bluray-720p
          - name: WEB 720p
            qualities:
              - WEBDL-720p
              - WEBRip-720p
              - HDTV-720p
      - name: HD - Anime
        reset_unmatched_scores:
          enabled: true
        upgrade:
          allowed: false
          until_quality: Remux-1080p
          until_score: 10000
        min_format_score: 100
        quality_sort: top
        qualities:
          - name: Remux-1080p
            qualities:
              - Bluray-1080p
              - Remux-1080p
          - name: WEB 1080p
            qualities:
              - WEBDL-1080p
              - WEBRip-1080p
              - HDTV-1080p
          - name: Bluray-720p
          - name: WEB 720p
            qualities:
              - WEBDL-720p
              - WEBRip-720p
              - HDTV-720p
          - name: Bluray-480p
          - name: WEB 480p
            qualities:
              - WEBDL-480p
              - WEBRip-480p
          - name: DVD
          - name: SDTV

    custom_formats:
      - trash_ids:
          # Audio
          - 496f355514737f7d83bf7aa4d24f8169 # TrueHD Atmos
          - 2f22d89048b01681dde8afe203bf2e95 # DTS X
          - 417804f7f2c4308c1f4c5d380d4c4475 # ATMOS (undefined)
          - 1af239278386be2919e1bcee0bde047e # DD+ ATMOS
          - 3cafb66171b47f226146a0770576870f # TrueHD
          - dcf3ec6938fa32445f590a4da84256cd # DTS-HD MA
          - a570d4a0e56a2874b64e5bfa55202a1b # FLAC
          - e7c2fcae07cbada050a0af3357491d7b # PCM
          - 8e109e50e0a0b83a5098b056e13bf6db # DTS-HD HRA
          - 185f1dd7264c4562b9022d963ac37424 # DD+
          - f9f847ac70a0af62ea4a08280b859636 # DTS-ES
          - 1c1a4c5e823891c75bc50380a6866f73 # DTS
          - 240770601cc226190c367ef59aba7463 # AAC
          - c2998bd0d90ed5621d8df281e839436e # DD

          # Movie Versions
          - 0f12c086e289cf966fa5948eac571f44 # Hybrid
          - 570bc9ebecd92723d2d21500f4be314c # Remaster
          - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
          - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
          - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
          - db9b4c4b53d312a3ca5f1378f6440fc9 # Vinegar Syndrome
          - 957d0f44b592285f26449575e8b1167e # Special Edition
          - eecf3a857724171f968a66cb5719e152 # IMAX
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced

          # HQ Release Groups
          - 3a3ff47579026e76d6504ebea39390de # Remux Tier 01
          - 9f98181fe5a3fbeb0cc29340da2a468a # Remux Tier 02
          - 8baaf0b3142bf4d94c42a724f034e27a # Remux Tier 03
          - c20f169ef63c5f40c2def54abaf4438e # WEB Tier 01
          - 403816d65392c79236dcb6dd591aeda4 # WEB Tier 02
          - af94e0fe497124d1f9ce732069ec8c3b # WEB Tier 03

          # Misc
          - e7718d7a3ce595f289bfee26adc178f5 # Repack/Proper
          - ae43b294509409a6a13919dedd4764c4 # Repack2

          # Unwanted
          - ed38b889b31be83fda192888e2286d83 # BR-DISK
          - 90a6f9a284dff5103f6346090e6280c8 # LQ
          - dc98083864ea246d05a42df0d05f81cc # x265 (HD)
          - b8cd450cbfa689c0259a01d9e29ba3d6 # 3D

          # Streaming Services
          - cc5e51a9e85a6296ceefe097a77f12f4 # BCORE
          - 2a6039655313bf5dab1e43523b62c374 # MA
          - 16622a6911d1ab5d5b8b713d5b0036d4 # CRiT
        assign_scores_to:
          - name: UHD
          - name: HD
          - name: SD

      # Custom Scoring
      - trash_ids:
          # Streaming Services
          - b3b3a6ac74ecbd56bcdbefa4799fb9df # AMZN
          - 40e9380490e748672c2522eaaeb692f7 # ATVP
          - f6ff65b3f4b464a79dcc75950fe20382 # CRAV
          - 84272245b2988854bfb76a16e60baea5 # DSNP
          - 509e5f41146e278f9eab1ddaceb34515 # HBO
          - 5763d1b0ce84aff3b21038eea8e9b8ad # HMAX
          - 526d445d4c16214309f0fd2b3be18a89 # Hulu
          - 6a061313d22e51e0f25b7cd4dc065233 # MAX
          - 170b1d363bd8516fbf3a3eb05d4faff6 # NF
          - fbca986396c5e695ef7b2def3c755d01 # OViD
          - bf7e73dd1d85b12cc527dc619761c840 # Pathe
          - c9fd353f8f5f1baf56dc601c4cb29920 # PCOK
          - e36a0ba1bc902b26ee40818a1d59b8bd # PMTP
          - c2863d2a50c9acad1fb50e53ece60817 # STAN
        assign_scores_to:
          - name: UHD
          - name: HD
          - name: SD
            score: 0

      ### Radarr Anime
      - trash_ids:
          # Anime CF/Scoring
          - fb3ccc5d5cc8f77c9055d4cb4561dded # Anime BD Tier 01 (Top SeaDex Muxers)
          - 66926c8fa9312bc74ab71bf69aae4f4a # Anime BD Tier 02 (SeaDex Muxers)
          - fa857662bad28d5ff21a6e611869a0ff # Anime BD Tier 03 (SeaDex Muxers)
          - f262f1299d99b1a2263375e8fa2ddbb3 # Anime BD Tier 04 (SeaDex Muxers)
          - ca864ed93c7b431150cc6748dc34875d # Anime BD Tier 05 (Remuxes)
          - 9dce189b960fddf47891b7484ee886ca # Anime BD Tier 06 (FanSubs)
          - 1ef101b3a82646b40e0cab7fc92cd896 # Anime BD Tier 07 (P2P/Scene)
          - 6115ccd6640b978234cc47f2c1f2cadc # Anime BD Tier 08 (Mini Encodes)
          - 8167cffba4febfb9a6988ef24f274e7e # Anime Web Tier 01 (Muxers)
          - 8526c54e36b4962d340fce52ef030e76 # Anime Web Tier 02 (Top FanSubs)
          - de41e72708d2c856fa261094c85e965d # Anime Web Tier 03 (Official Subs)
          - 9edaeee9ea3bcd585da9b7c0ac3fc54f # Anime Web Tier 04 (Official Subs)
          - 22d953bbe897857b517928f3652b8dd3 # Anime Web Tier 05 (FanSubs)
          - a786fbc0eae05afe3bb51aee3c83a9d4 # Anime Web Tier 06 (FanSubs)
          - b0fdc5897f68c9a68c70c25169f77447 # Anime LQ Groups
          - c259005cbaeb5ab44c06eddb4751e70c # v0
          - 5f400539421b8fcf71d51e6384434573 # v1
          - 3df5e6dfef4b09bb6002f732bed5b774 # v2
          - db92c27ba606996b146b57fbe6d09186 # v3
          - d4e5e842fad129a3c097bdb2d20d31a0 # v4
          # Anime Streaming Services
          - 60f6d50cbd3cfc3e9a8c00e3a30c3114 # VRV
        assign_scores_to:
          - name: HD - Anime

      # Custom Scoring
      # Anime CF/Scoring
      - trash_ids:
          - 9172b2f683f6223e3a1846427b417a3d # VOSTFR
        assign_scores_to:
          - name: HD - Anime
            score: -10000

      # Main Guide Remux Tier Scoring
      - trash_ids:
          - 3a3ff47579026e76d6504ebea39390de # Remux Tier 01
        assign_scores_to:
          - name: HD - Anime
            score: 1050 # required as this differs from the standard scoring

      - trash_ids:
          - 9f98181fe5a3fbeb0cc29340da2a468a # Remux Tier 02
        assign_scores_to:
          - name: HD - Anime
            score: 1000 # required as this differs from the standard scoring

      - trash_ids:
          - 8baaf0b3142bf4d94c42a724f034e27a # Remux Tier 03
        assign_scores_to:
          - name: HD - Anime
            score: 950 # required as this differs from the standard scoring

      # Main Guide WEB Tier Scoring
      - trash_ids:
          - c20f169ef63c5f40c2def54abaf4438e # WEB Tier 01
        assign_scores_to:
          - name: HD - Anime
            score: 350 # required as this differs from the standard scoring

      - trash_ids:
          - 403816d65392c79236dcb6dd591aeda4 # WEB Tier 02
        assign_scores_to:
          - name: HD - Anime
            score: 300 # required as this differs from the standard scoring

      - trash_ids:
          - af94e0fe497124d1f9ce732069ec8c3b # WEB Tier 03
        assign_scores_to:
          - name: HD - Anime
            score: 250 # required as this differs from the standard scoring

      # Adjustable scoring section
      - trash_ids:
          - 06b6542a47037d1e33b15aa3677c2365 # Anime Raws
        assign_scores_to:
          - name: HD - Anime
            score: -10000 # adjust as desired

      - trash_ids:
          - 064af5f084a0a24458cc8ecd3220f93f # Uncensored
        assign_scores_to:
          - name: HD - Anime
            score: 0 # adjust as desired

      - trash_ids:
          - a5d148168c4506b55cf53984107c396e # 10bit
        assign_scores_to:
          - name: HD - Anime
            score: 0 # adjust as desired

      - trash_ids:
          - 4a3b087eea2ce012fcc1ce319259a3be # Anime Dual Audio
        assign_scores_to:
          - name: HD - Anime
            score: 0 # adjust as desired

      - trash_ids:
          - b23eae459cc960816f2d6ba84af45055 # Dubs Only
        assign_scores_to:
          - name: HD - Anime
            score: -10000 # adjust as desired
