metadata_dir = "/data/meta"
data_dir = "/data/data"
db_engine = "lmdb"
metadata_auto_snapshot_interval = "6h"

replication_factor = 1
compression_level = "none"

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"

[s3_api]
s3_region = "eu-east-1"
api_bind_addr = "[::]:3900"
root_domain = ".garage.ishioni.casa"

[admin]
api_bind_addr = "[::]:3903"
