---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-secret.yaml
  - grafana-dashboard.yaml
  - postgres-v1-cluster.yaml
  - prometheus.yaml
  - scheduledbackup.yaml
  - loadbalancer.yaml
