---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - calico-system.yaml
  - database.yaml
  - fileservers.yaml
  - games.yaml
  - storage.yaml
  - reverse-proxy.yaml
  - security.yaml
  - media.yaml
  - monitoring.yaml
  - nextcloud.yaml
