---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - external-dns.yaml
  - ingress.yaml
  - storage.yaml
  - reverse-proxy.yaml
  - security.yaml
  - media.yaml
  - minecraft.yaml
  - monitoring.yaml
  - nextcloud.yaml
